@startuml repl
' skinparam maxMessageSize 125

actor User as "Blocking IO Service"
actor Ctrl as "Control"
actor Eval as "Evaluator"
actor Cmd1 as "Cmd Evaluator 1"
actor Cmd2 as "Cmd Evaluator 2"

== Regular Input Handling ==

autonumber
User -> Ctrl : ""Load("<INPUT>")""
Ctrl -> Eval : ""Evaluate("<INPUT>")""
Eval -> Ctrl : ""Print("<OUTPUT>")""

== Command Handling ==

autonumber
User -> Ctrl : ""Load(":cmd1 <INPUT>")""
Ctrl -> Cmd1 : ""Evaluate(":cmd1 <INPUT>")""
Cmd1 -> Ctrl : ""Print("<OUTPUT>")""

== Command Handling with Config ==

autonumber
User -> Ctrl : ""Load(":cmd2 <INPUT>")""
Ctrl -> Cmd2 : ""Evaluate(":cmd2 <INPUT>")""
Cmd2 -> Ctrl : ""GetConfigMut""
Ctrl -> User : ""GetConfigMut""
User -> Ctrl : ""ConfigMut(&mut Config)""
Ctrl -> Cmd2 : ""ConfigMut(&mut Config)""
Cmd2 -> Ctrl : ""Print("<OUTPUT>")""

@enduml